name: landfalling_ar_mfw
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - netcdf4
  - cftime
  - matplotlib
  - cartopy
  - shapely
  - pyproj
  - metpy
  - siphon
  - scipy
  - dask
